version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rusteze
      POSTGRES_DB: rusteze
    ports:
      - "5432:5432"
  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - 9042:9042
    restart: always